classdef ReferenceEllipsoid < Ellipsoid
    properties
        Name string
    end
    properties (GetAccess = private, Constant = true)
        Ellipsoid = struct( ...
            "GRS80", struct( ...
                    "Name", "Geodetic Reference System 1980", ...
                    "SemimajorAxis", 6378137, ...
                    "SemiminorAxis", 6356752.314140347, ...
                    "InverseFlattening", 298.2572221008827), ...
            "HAYFORD", struct( ...
                    "Name", "Hayford 1909", ...
                    "SemimajorAxis", 6378388, ...
                    "SemiminorAxis", 6356911.94613, ...
                    "InverseFlattening", 297) ...
        );
    end
    methods
        function this = ReferenceEllipsoid(nm)
            format longG;
            name = upper(nm);
            reference = this.Ellipsoid.(name);
            this.Name = reference.Name;
            this.SemimajorAxis = reference.SemimajorAxis;
            this.SemiminorAxis = reference.SemiminorAxis;
            this.InverseFlattening = reference.InverseFlattening;
        end
    end
end